#!/usr/bin/env python3
"""
EDA: Exploratory Data Analysis for Streetscope Project
=========================================================
Produces diagnostic plots and console stats from analysis_data.parquet files.

Outputs (all in figs/):
  - eda_temporal_coverage.pdf      Hour/day-of-week distributions
  - eda_crowd_size_distribution.pdf  Histogram of total_people

Note: GPS coverage maps are generated by 11_make_maps.py with proper basemaps.

Usage:
    python scripts/09_eda.py --cities mumbai,navi_mumbai
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.ticker import PercentFormatter

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data"
FIGS = ROOT / "figs"
FIGS.mkdir(parents=True, exist_ok=True)

from figstyle import ACCENT, ACCENT_CMAP, GRAYS, MARKERS, apply_style  # noqa: E402

apply_style()


def load_all_cities(cities: list[str]) -> pd.DataFrame:
    """Load and concat analysis_data.parquet for each city."""
    dfs = []
    for city in cities:
        path = OUTPUT / city / "analysis_data.parquet"
        if not path.exists():
            print(f"WARNING: {path} not found, skipping")
            continue
        df = pd.read_parquet(path)
        df["city"] = city
        dfs.append(df)
    if not dfs:
        raise FileNotFoundError("No data found for any city")
    return pd.concat(dfs, ignore_index=True)


def print_data_summary(df: pd.DataFrame) -> None:
    """Print row counts, GPS coverage %, temporal range per city."""
    print("\n" + "=" * 60)
    print("DATA SUMMARY")
    print("=" * 60)

    for city in df["city"].unique():
        sub = df[df["city"] == city]
        n_rows = len(sub)
        n_people = sub["total_people"].sum()
        gps_coverage = sub["gps_valid"].mean() * 100

        if "frame_datetime" in sub.columns and sub["frame_datetime"].notna().any():
            date_min = sub["frame_datetime"].min()
            date_max = sub["frame_datetime"].max()
            date_range = f"{date_min} to {date_max}"
        else:
            date_range = "N/A"

        print(f"\n{city}:")
        print(f"  Rows: {n_rows:,}")
        print(f"  Total people: {n_people:,}")
        print(f"  GPS coverage: {gps_coverage:.1f}%")
        print(f"  Date range: {date_range}")


def print_field_completeness(df: pd.DataFrame) -> None:
    """Print % non-null for each annotation field by city."""
    print("\n" + "=" * 60)
    print("FIELD COMPLETENESS")
    print("=" * 60)

    annotation_fields = [
        "men_count",
        "women_count",
        "men_twowheeler",
        "women_twowheeler",
        "footpath",
        "lane_markings",
        "potholes",
        "litter",
        "bus_station",
        "railway_station",
        "street_vendor",
        "itinerary_road_type",
        "gps_lat",
        "gps_lon",
    ]

    for city in df["city"].unique():
        sub = df[df["city"] == city]
        print(f"\n{city}:")
        for field in annotation_fields:
            if field in sub.columns:
                pct = sub[field].notna().mean() * 100
                print(f"  {field}: {pct:.1f}%")


def print_headline_numbers(df: pd.DataFrame) -> None:
    """Print primary pedestrian and secondary combined-mode summaries."""
    print("\n" + "=" * 60)
    print("HEADLINE NUMBERS")
    print("=" * 60)

    for city in df["city"].unique():
        sub = df[df["city"] == city]

        total_people = sub["total_people"].sum()
        total_women = sub["total_women"].sum()
        total_men = sub["total_men"].sum()

        weighted_prop = total_women / total_people if total_people > 0 else 0

        valid_images = sub[sub["total_people"] > 0]
        image_level_mean = valid_images["prop_women"].mean() if len(valid_images) > 0 else 0

        sex_ratio = (total_women / total_men * 1000) if total_men > 0 else 0

        pedestrians_women = sub["women_count"].sum()
        pedestrians_men = sub["men_count"].sum()
        ped_prop = (
            pedestrians_women / (pedestrians_women + pedestrians_men)
            if (pedestrians_women + pedestrians_men) > 0
            else 0
        )
        ped_sex_ratio = (pedestrians_women / pedestrians_men * 1000) if pedestrians_men > 0 else 0

        print(f"\n{city}:")
        print(f"  Total people: {total_people:,}")
        print(f"  Total women: {total_women:,}")
        print(f"  Combined-mode female share: {weighted_prop:.4f} ({weighted_prop * 100:.2f}%)")
        print(f"  Combined-mode image mean: {image_level_mean:.4f} ({image_level_mean * 100:.2f}%)")
        print(f"  Sex ratio (women per 1000 men): {sex_ratio:.1f}")
        print(f"  Primary pedestrian female share: {ped_prop:.4f} ({ped_prop * 100:.2f}%)")
        print(f"  Pedestrian sex ratio: {ped_sex_ratio:.1f}")


def plot_gps_coverage(df: pd.DataFrame, city: str, out_dir: Path) -> None:
    """Scatter plot of GPS points colored by prop_women. Output: eda_gps_coverage_{city}.pdf"""
    sub = df[(df["city"] == city) & df["gps_valid"]].copy()

    if len(sub) == 0:
        print(f"  WARNING: No GPS data for {city}, skipping GPS coverage plot")
        return

    sub_valid = sub[sub["total_people"] > 0].copy()

    fig, ax = plt.subplots(figsize=(6, 5))

    sc = ax.scatter(
        sub_valid["gps_lon"],
        sub_valid["gps_lat"],
        c=sub_valid["prop_women"],
        cmap=ACCENT_CMAP,
        vmin=0,
        vmax=0.5,
        s=15,
        alpha=0.6,
        edgecolors="none",
    )

    cbar = fig.colorbar(sc, ax=ax, shrink=0.7)
    cbar.set_label("Proportion women", fontsize=8)

    ax.set_xlabel("Longitude")
    ax.set_ylabel("Latitude")
    ax.set_title(
        f"GPS Coverage: {city.replace('_', ' ').title()}\n(n={len(sub_valid):,} images with GPS & people)"
    )

    ax.set_aspect("equal", adjustable="box")

    out_path = out_dir / f"eda_gps_coverage_{city}.pdf"
    fig.savefig(out_path)
    plt.close(fig)
    print(f"  -> {out_path.name}")


def plot_temporal_coverage(df: pd.DataFrame, out_dir: Path) -> None:
    """Histograms of hour/day-of-week distribution. Output: eda_temporal_coverage.pdf"""
    fig, axes = plt.subplots(1, 2, figsize=(8, 3.5))

    ax = axes[0]
    with_hour = df[df["frame_hour"].notna()].copy()
    with_hour["hour_bin"] = with_hour["frame_hour"].astype(int)
    cities = list(with_hour["city"].unique())
    hours = list(range(with_hour["hour_bin"].min(), with_hour["hour_bin"].max() + 1))
    counts = (
        with_hour.groupby(["city", "hour_bin"])
        .size()
        .unstack(fill_value=0)
        .reindex(index=cities, columns=hours, fill_value=0)
    )

    masked = np.ma.masked_equal(counts.values, 0)
    cmap = plt.get_cmap("Greys").copy()
    cmap.set_bad("#f5f5f5")
    ax.imshow(masked, cmap=cmap, aspect="auto", vmin=0)
    for i in range(len(cities)):
        for j in range(len(hours)):
            n = counts.values[i, j]
            if n == 0:
                continue
            dark = n > 0.55 * counts.values.max()
            ax.text(
                j,
                i,
                str(n),
                ha="center",
                va="center",
                fontsize=5.5,
                color="white" if dark else "#333333",
            )
    ax.set_xticks(range(len(hours)))
    ax.set_xticklabels(hours, fontsize=6)
    ax.set_yticks(range(len(cities)))
    ax.set_yticklabels([c.replace("_", " ").title() for c in cities], fontsize=7)
    ax.set_xlabel("Hour of day (IST)")
    ax.set_title("Images by hour")
    ax.tick_params(length=0)
    for spine in ax.spines.values():
        spine.set_visible(False)

    ax = axes[1]
    day_names = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    cities = list(df["city"].unique())
    n = len(cities)
    width = 0.8 / n
    x = np.arange(7)
    for i, city in enumerate(cities):
        sub = df[(df["city"] == city) & df["frame_dayofweek"].notna()]
        if len(sub) == 0:
            continue
        counts = sub["frame_dayofweek"].value_counts().reindex(range(7), fill_value=0)
        ax.bar(
            x + (i - (n - 1) / 2) * width,
            counts.values,
            width,
            alpha=0.9,
            label=city.replace("_", " ").title(),
            color=GRAYS.get(city, "0.5"),
        )
    ax.set_xlabel("Day of week")
    ax.set_ylabel("Number of images")
    ax.set_title("Distribution by day")
    ax.set_xticks(x)
    ax.set_xticklabels(day_names)
    ax.legend(fontsize=7, frameon=False)

    fig.tight_layout()
    out_path = out_dir / "eda_temporal_coverage.pdf"
    fig.savefig(out_path)
    plt.close(fig)
    print(f"  -> {out_path.name}")


def plot_crowd_size_distribution(df: pd.DataFrame, out_dir: Path) -> None:
    """Histogram of total_people per image. Output: eda_crowd_size_distribution.pdf"""
    fig, ax = plt.subplots(figsize=(6, 4))

    max_people = min(df["total_people"].max(), 50)
    bins = np.arange(-0.5, max_people + 1.5, 1)

    for city in df["city"].unique():
        sub = df[df["city"] == city]
        people = sub["total_people"]
        label = (
            f"{city.replace('_', ' ').title()} "
            f"(mean {people.mean():.1f}, median {people.median():.0f})"
        )
        ax.hist(
            people.clip(upper=max_people),
            bins=bins,
            histtype="step",
            linewidth=1.2,
            label=label,
            color=GRAYS.get(city, "0.5"),
        )

    ax.set_xlabel("Total people per image")
    ax.set_ylabel("Number of images")
    ax.set_title("Crowd size distribution")
    ax.legend(fontsize=7, frameon=False)

    fig.tight_layout()
    out_path = out_dir / "eda_crowd_size_distribution.pdf"
    fig.savefig(out_path)
    plt.close(fig)
    print(f"  -> {out_path.name}")


def plot_prop_female_vs_crowd(df: pd.DataFrame, out_dir: Path) -> None:
    """Scatter of prop_women vs total_people. Output: eda_prop_female_vs_crowd.pdf"""
    fig, ax = plt.subplots(figsize=(6, 4))

    valid = df[df["total_people"] > 0].copy()

    for city in valid["city"].unique():
        sub = valid[valid["city"] == city]
        ax.scatter(
            sub["total_people"],
            sub["prop_women"],
            alpha=0.3,
            s=10,
            marker=MARKERS.get(city, "o"),
            label=city.replace("_", " ").title(),
            color=GRAYS.get(city, "0.5"),
        )

    ax.axhline(0.5, color=ACCENT, linestyle="--", linewidth=0.8, label="Parity")

    ax.set_xlabel("Total people per image")
    ax.set_ylabel("Percent women")
    ax.set_title("Percent women vs. crowd size")
    ax.set_ylim(-0.05, 1.05)
    ax.yaxis.set_major_formatter(PercentFormatter(xmax=1, decimals=0))
    ax.legend(fontsize=7, frameon=False)

    fig.tight_layout()
    out_path = out_dir / "eda_prop_female_vs_crowd.pdf"
    fig.savefig(out_path)
    plt.close(fig)
    print(f"  -> {out_path.name}")


def main():
    parser = argparse.ArgumentParser(description="EDA for Streetscope project")
    parser.add_argument(
        "--cities",
        type=str,
        default="mumbai,navi_mumbai,bangalore,delhi",
        help="Comma-separated list of cities (default: mumbai,navi_mumbai)",
    )
    args = parser.parse_args()

    cities = [c.strip() for c in args.cities.split(",")]

    print("=" * 60)
    print("STREETSCOPE: EXPLORATORY DATA ANALYSIS")
    print("=" * 60)
    print(f"Cities: {cities}")

    df = load_all_cities(cities)
    print(f"\nLoaded {len(df):,} total rows")

    print_data_summary(df)
    print_field_completeness(df)
    print_headline_numbers(df)

    print("\n" + "=" * 60)
    print("GENERATING PLOTS")
    print("=" * 60)

    plot_temporal_coverage(df, FIGS)
    plot_crowd_size_distribution(df, FIGS)

    print("\n" + "=" * 60)
    print(f"EDA COMPLETE. Outputs in: {FIGS}")
    print("=" * 60)


if __name__ == "__main__":
    main()
